version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_sql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
